# Generated by Django 3.1.7 on 2021-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210328_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='Image_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='doc',
            name='text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
