# Generated by Django 3.1.7 on 2021-04-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210401_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='Image_name',
            new_name='Image_Name',
        ),
    ]
